import { useState } from "react";
import axios from "axios";
import { useAuthState } from "react-firebase-hooks/auth";
import { useNavigate } from "react-router-dom";
import { ArrowRight, FileCheck2 } from "lucide-react";
import { auth } from "../../firebase";
import { MuseumPageHero } from "../museum/MuseumPage";

const SERVER_URL=import.meta.env.VITE_SERVER_URL || "https://historia-backend-ycj7.onrender.com";
export default function NewBot(){const navigate=useNavigate();const[user]=useAuthState(auth);const[formData,setFormData]=useState({name:"",greeting:"",description:"",additionalMessage:""});const[loading,setLoading]=useState(false);const[error,setError]=useState("");
 const handleChange=event=>setFormData(previous=>({...previous,[event.target.name]:event.target.value}));
 const handleSubmit=async event=>{event.preventDefault();if(!formData.name||!formData.greeting||!formData.description)return;setLoading(true);setError("");try{const response=await axios.post(`${SERVER_URL}/api/create-new-bot`,{...formData,creator:user?.displayName||user?.email||"Unknown",creatorId:user?.uid});if(response.status===200)navigate("/submitted");}catch(submitError){console.error(submitError);setError("The proposal could not be submitted. Please try again shortly.");setLoading(false);}};
 return <><MuseumPageHero index="01" eyebrow="COLLECTION PROPOSAL" title="Propose a voice" italic="for the archive." description="Recommend a well-documented historical figure whose life could open a meaningful conversation for future visitors." image="/images/art5.png" imageAlt="Archival illustration of a writing quill over handwritten notes"/>
 <main className="mp-section mp-section-light"><div className="mp-form-layout"><form className="mp-form" onSubmit={handleSubmit}><p className="mp-index">ACCESSION FORM / 01</p><div className="mp-field"><label htmlFor="figure-name">Historical figure</label><input id="figure-name" name="name" value={formData.name} onChange={handleChange} placeholder="Full name" required/></div><div className="mp-field"><label htmlFor="figure-greeting">Opening words</label><textarea id="figure-greeting" name="greeting" rows="4" value={formData.greeting} onChange={handleChange} placeholder="How might this person welcome a visitor, in their own period and voice?" required/></div><div className="mp-field"><label htmlFor="figure-description">Biographical case</label><textarea id="figure-description" name="description" rows="7" value={formData.description} onChange={handleChange} placeholder="Describe their life, historical significance, and the questions they could help visitors explore." required/></div><div className="mp-field"><label htmlFor="figure-additional">Sources and additional context</label><textarea id="figure-additional" name="additionalMessage" rows="5" value={formData.additionalMessage} onChange={handleChange} placeholder="Suggested biographies, primary sources, contemporaries, or interpretive cautions."/></div>{error&&<p className="mp-form-error">{error}</p>}<button className="mp-button" disabled={loading}>{loading?"Submitting proposal…":<>Submit for review <ArrowRight/></>}</button></form><aside className="mp-aside-note"><FileCheck2/><h3>Accession criteria</h3><ol><li>The figure has a meaningful public or historical record.</li><li>Enough reliable source material exists to support interpretation.</li><li>The proposed greeting reflects period, personality, and context.</li><li>The conversation offers more than simple biographical facts.</li></ol><p>Every proposal is reviewed before entering the public collection.</p></aside></div></main></>}
