import { useState } from "react";
import axios from "axios";
import { useNavigate } from "react-router-dom";
import { useAuthState } from "react-firebase-hooks/auth";
import { ArrowRight, Mail, MessageSquareText } from "lucide-react";
import { auth } from "../../firebase";
import { MuseumPageHero } from "../museum/MuseumPage";

const SERVER_URL=import.meta.env.VITE_SERVER_URL || "https://historia-backend-ycj7.onrender.com";
export default function Feedback(){const[user]=useAuthState(auth);const navigate=useNavigate();const[formData,setFormData]=useState({title:"",email:"",description:""});const[submitting,setSubmitting]=useState(false);const[error,setError]=useState("");
  const handleChange=event=>setFormData(previous=>({...previous,[event.target.name]:event.target.value}));
  const sendFeedback=async event=>{event.preventDefault();if(!formData.title.trim()||!formData.description.trim())return;setSubmitting(true);setError("");try{const response=await axios.post(`${SERVER_URL}/api/feedback`,{senderUid:user?.uid||null,senderEmail:user?.email||null,...formData});if(response.status===200)navigate(user?"/user":"/");}catch(submitError){console.error("There was an error submitting feedback",submitError);setError("Your note could not be delivered. Please try again shortly.");setSubmitting(false);}};
  return <><MuseumPageHero index="01" eyebrow="VISITOR CORRESPONDENCE" title="Help shape" italic="the archive." description="Every thoughtful observation helps us make the collection clearer, more responsible, and more rewarding to explore." image="/images/art4.png" imageAlt="Expressive black ink and ochre manuscript study"/>
  <main className="mp-section mp-section-light"><div className="mp-form-layout"><form className="mp-form" onSubmit={sendFeedback}><p className="mp-index">SEND A NOTE</p><div className="mp-field"><label htmlFor="feedback-title">Subject</label><input id="feedback-title" name="title" value={formData.title} onChange={handleChange} placeholder="What should we know?" required/></div><div className="mp-field"><label htmlFor="feedback-email">Reply address</label><input id="feedback-email" name="email" type="email" value={formData.email} onChange={handleChange} placeholder={user?.email||"you@example.com"}/></div><div className="mp-field"><label htmlFor="feedback-description">Your observation</label><textarea id="feedback-description" name="description" rows="8" value={formData.description} onChange={handleChange} placeholder="Tell us what worked, what felt unclear, or what you hope to see next." required/></div>{error&&<p className="mp-form-error">{error}</p>}<button className="mp-button" disabled={submitting}>{submitting?"Delivering note…":<>Send correspondence <ArrowRight/></>}</button></form><aside className="mp-aside-note"><Mail/><h3>Visitor services</h3><p>We read every message. Feedback about historical accuracy, accessibility, and collection gaps is especially valuable.</p><ul><li>Report an inaccurate or confusing response</li><li>Suggest a figure or subject area</li><li>Share an accessibility concern</li><li>Tell us about your visit</li></ul><div className="mp-contact-mark"><MessageSquareText/><span>Responses may take several days.</span></div></aside></div></main></>}
