import { Helmet } from "react-helmet-async";
import { ArrowRight, Building2, GraduationCap, Library, Users } from "lucide-react";
import Navbar from "../../components/navbar/navbar";
import { MuseumFooter, MuseumPageHero } from "../../components/museum/MuseumPage";

const partners=[{icon:<GraduationCap/>,title:'Schools and educators',text:'Create inquiry-led lessons, seminar preparation, and writing prompts that place students inside historical decisions.'},{icon:<Library/>,title:'Libraries and museums',text:'Extend exhibitions and collections with conversational interpretation that invites visitors to stay curious after they leave.'},{icon:<Building2/>,title:'Cultural institutions',text:'Develop focused historical experiences around anniversaries, archives, local histories, and public programs.'},{icon:<Users/>,title:'Research communities',text:'Explore responsible ways to make documented lives and historical questions more accessible to broad audiences.'}];
export default function Partners(){return <div className="mp-page"><Helmet><title>Institutional Partnerships | Echoes of History</title><meta name="description" content="Partner with Echoes of History on education, exhibitions, and public historical interpretation."/></Helmet><Navbar/><MuseumPageHero index="01" eyebrow="INSTITUTIONAL PARTNERSHIPS" title="Bring the archive" italic="into your institution." description="We collaborate with educators, libraries, museums, and cultural organizations to create thoughtful encounters with history." image="/images/art2.png" imageAlt="Architectural illustration of a classical stone arch"><a className="mp-button" href="mailto:partnerships@echoesofhistoryai.org">Begin a conversation <ArrowRight/></a></MuseumPageHero>
  <section className="mp-section mp-section-light"><div className="mp-section-heading"><p className="mp-index">02 / WHO WE WORK WITH</p><h2>Built for places where questions matter.</h2></div><div className="partner-grid">{partners.map((item,index)=><article key={item.title}><div>{item.icon}</div><span>0{index+1}</span><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></section>
  <section className="partner-process"><div><p className="mp-index">03 / A SHARED PROCESS</p><h2>From collection to encounter.</h2></div><ol>{[['01','Listen','We begin with your audience, collection, learning goals, and standards for interpretation.'],['02','Curate','Together we identify figures, source material, themes, and the questions worth opening.'],['03','Shape','We build and review a focused visitor experience with clear historical and educational framing.'],['04','Learn','A pilot reveals how visitors engage and where the experience should deepen.']].map(row=><li key={row[0]}><span>{row[0]}</span><strong>{row[1]}</strong><p>{row[2]}</p></li>)}</ol></section>
  <section className="mp-cta"><p className="mp-index">BEGIN A PARTNERSHIP</p><h2>What history could your audience enter?</h2><a className="mp-button" href="mailto:partnerships@echoesofhistoryai.org">Write to us <ArrowRight/></a></section><MuseumFooter/></div>}
